worker_processes 1;

error_log /tmp/team1_nginx_error.log info;
pid /tmp/team1_nginx.pid;

events {
    worker_connections 256;
}

http {
    access_log /tmp/team1_nginx_access.log;

    upstream backend_pool {
        server 10.7.27.207:3001 max_fails=1 fail_timeout=5s;
        server 10.7.19.238:3002 max_fails=1 fail_timeout=5s;
    }

    server {
        listen 8443 ssl;

        server_name app.team1.test api.team1.test;

        ssl_certificate /Users/luffy/cn-project/team1-server.crt;
        ssl_certificate_key /Users/luffy/cn-project/team1-server.key;

        ssl_protocols TLSv1.2;

        location / {
            proxy_pass http://backend_pool;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}